services:
  cowrie:
    image: ghcr.io/cowrie/cowrie:latest
    container_name: cowrie_honeypot
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - ./cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
      - ./banner.txt:/cowrie/cowrie-git/share/cowrie/banner.txt
      - ./file/motd:/cowrie/cowrie-git/honeyfs/etc/motd
      - ./file/df:/cowrie/cowrie-git/share/cowrie/txtcmds/bin/df  

    environment:
      - COWRIE_CONFIGFILE=/cowrie/cowrie-git/etc/cowrie.cfg
